spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWD}
spring.jpa.show-sql=true

key.jwt=${JWT_KEY}

server.error.include-stacktrace=never